# Generated by Django 2.2.28 on 2022-09-01 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_baseapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
