# Generated by Django 2.2.28 on 2022-09-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_baseapp', '0005_auto_20220902_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
