# Generated by Django 2.2.28 on 2022-09-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_baseapp', '0006_auto_20220904_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=0, max_digits=5)),
            ],
        ),
    ]
