# Generated by Django 2.2.28 on 2022-09-06 15:05

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True, max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=35)),
                ('slug', models.SlugField(blank=True, max_length=35, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True, max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('article', models.CharField(db_index=True, max_length=20)),
                ('preview_image', models.ImageField(blank=True, upload_to='media/shop_gallery/preview')),
                ('price', models.DecimalField(decimal_places=0, max_digits=5)),
                ('available', models.BooleanField(default=True)),
                ('short_description', models.TextField(blank=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_category', to='barber_shop.Category')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_group', to='barber_shop.ProductGroup')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_name', to='barber_shop.Manufacturer')),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='media/shop_gallery')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='barber_shop.Product')),
            ],
        ),
    ]
